algoritmo "semnome"
// Função :
// Autor : Davi dos Santos Silva
// Data : 16/05/2022
// Seção de Declarações 
var
Resto: inteiro
Resultado: real
Dividendo: inteiro

inicio
// Seção de Comandos 
,

3
Resto <- 121 mod 2
Resultado <- 121/2
escreval ("o resultado da operação é :", Resultado)
escreval ("o resto dessa operação é :", Resto)
Dividendo <- 121 div 2
escreval ("o dividendo dessa operação é :", Dividendo)
fimalgoritmo                                  j
